name: "Web Megaphone"
version: "0.72"
slug: "web_megaphone"
description: "Web PA System"
url: "https://github.com/netmms/ha_netmms/tree/main/web_megaphone"

# Icons to show in the Home Assistant Add-on Store
logo: "https://raw.githubusercontent.com/netmms/ha_netmms/main/web_megaphone/logo.png"
icon: "https://raw.githubusercontent.com/netmms/ha_netmms/main/web_megaphone/icon.png"

init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

stdin: true
audio: true

host_network: true

ports:
  8000/tcp: 8000
  8001/tcp: 8001

map:
  - share:rw
  - config:rw

options:
  volume1: 40
  volume2: 80

schema:
  volume1: int
  volume2: int
